apiVersion: v1
kind: Pod
metadata:
  name: customer-pod
spec:
  containers:
  - name: customer
    image: 953548863399.dkr.ecr.us-east-2.amazonaws.com/customer:latest
    ports:
    - containerPort: 8081 
